[workspace]
resolver = "2"
members = [
    "crates/toku-core",
    "crates/toku-db",
    "crates/toku-meta",
    "crates/toku-import",
    "crates/toku-export",
    "crates/toku-cli",
]

[workspace.package]
version = "0.2.1"
edition = "2024"
authors = ["kafkade"]
license = "MIT"
repository = "https://github.com/kafkade/toku"

[workspace.dependencies]
toku-core = { path = "crates/toku-core", version = "0.2.1" }
toku-db = { path = "crates/toku-db", version = "0.2.1" }
toku-meta = { path = "crates/toku-meta", version = "0.2.1" }
toku-import = { path = "crates/toku-import", version = "0.2.1" }
toku-export = { path = "crates/toku-export", version = "0.2.1" }
thiserror = "2"
uuid = { version = "1", features = ["v7", "serde"] }
chrono = { version = "0.4", default-features = false, features = ["std", "clock", "serde"] }
rusqlite = { version = "0.38", features = ["bundled", "column_decltype"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["rt", "macros"] }
toml = "1.1"
