[package]
name = "toku-cli"
description = "CLI interface for Toku personal book manager"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "toku"
path = "src/main.rs"

[dependencies]
toku-core = { path = "../toku-core", version = "0.1.0" }
toku-db = { path = "../toku-db", version = "0.1.0" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
