#ifndef TOKU_H
#define TOKU_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Result codes returned by all FFI functions.
 */
typedef enum TokuStatus {
  /**
   * Operation succeeded.
   */
  TOKU_STATUS_OK = 0,
  /**
   * A required pointer argument was null.
   */
  TOKU_STATUS_ERROR_NULL_POINTER = 1,
  /**
   * An input string was not valid UTF-8.
   */
  TOKU_STATUS_ERROR_INVALID_UTF8 = 2,
  /**
   * The requested resource was not found.
   */
  TOKU_STATUS_ERROR_NOT_FOUND = 3,
  /**
   * A database or I/O error occurred.
   */
  TOKU_STATUS_ERROR_DB = 4,
  /**
   * A Rust panic was caught at the FFI boundary.
   */
  TOKU_STATUS_ERROR_PANIC = 5,
  /**
   * A sync operation failed (network, auth, configuration, or merge error).
   */
  TOKU_STATUS_ERROR_SYNC = 6,
} TokuStatus;

/**
 * Opaque handle to an open Toku database. Created by `toku_open`, destroyed by
 * `toku_close`. Do not inspect or modify the contents from C/Swift.
 */
typedef struct TokuDb TokuDb;

/**
 * Retrieve the last error message for the current thread. Returns null if no error
 * has occurred since the last successful call. The returned pointer is valid until
 * the next FFI call on this thread — do not free it.
 *
 * # Safety
 * This function accesses thread-local storage and returns a pointer that is valid
 * only until the next FFI call on the same thread.
 */
const char *toku_last_error(void);

/**
 * Open (or create) a Toku database at the given file path.
 * On success, writes a handle to `*out`. The caller must eventually call `toku_close`.
 *
 * # Safety
 * - `path` must be a valid NUL-terminated UTF-8 string.
 * - `out` must be a valid pointer to a `*mut TokuDb`.
 */
enum TokuStatus toku_open(const char *path, struct TokuDb **out);

/**
 * Open (or create) an **encrypted** Toku database at `path`, unlocking it with
 * a raw 256-bit key.
 *
 * `key` must point to exactly 32 bytes (the Argon2id-derived key; the caller
 * derives it from the user's passphrase). On success, writes a handle to
 * `*out`. The caller must eventually call `toku_close`. A wrong key fails
 * cleanly with `TokuStatus::ErrorDb` (see `toku_last_error`), never a crash.
 *
 * This function is only functional in builds compiled with the `sqlcipher`
 * feature; otherwise it returns `TokuStatus::ErrorDb` with an explanatory
 * message. `toku_open` is unaffected and continues to open plaintext databases.
 *
 * # Safety
 * - `path` must be a valid NUL-terminated UTF-8 string.
 * - `key` must point to `key_len` readable bytes.
 * - `out` must be a valid pointer to a `*mut TokuDb`.
 */
enum TokuStatus toku_open_encrypted(const char *path,
                                    const uint8_t *key,
                                    uintptr_t key_len,
                                    struct TokuDb **out);

/**
 * Close a Toku database handle and free its resources.
 * After this call, the handle must not be used. Passing null is a safe no-op.
 *
 * # Safety
 * `db` must be a handle previously returned by `toku_open`, or null.
 */
void toku_close(struct TokuDb *db);

/**
 * Add a book with a title and optional author. On success, writes the new book's
 * UUID string to `*out_id`. The caller must free `*out_id` with `toku_free_string`.
 *
 * Pass null for `author` to add a book without an author.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `title` must be a valid NUL-terminated UTF-8 string.
 * - `author` may be null, or a valid NUL-terminated UTF-8 string.
 * - `out_id` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_add_book(struct TokuDb *db,
                              const char *title,
                              const char *author,
                              char **out_id);

/**
 * List all books as a JSON array string. On success, writes the JSON string to
 * `*out_json`. The caller must free `*out_json` with `toku_free_string`.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_list_books(struct TokuDb *db, char **out_json);

/**
 * Get a single book by UUID as a JSON string. On success, writes the JSON string to
 * `*out_json`. Returns `ErrorNotFound` if no book matches the ID.
 * The caller must free `*out_json` with `toku_free_string`.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `id` must be a valid NUL-terminated UUID string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_get_book(struct TokuDb *db, const char *id, char **out_json);

/**
 * Delete a book by UUID. Returns `ErrorNotFound` if no book matches.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `id` must be a valid NUL-terminated UUID string.
 */
enum TokuStatus toku_delete_book(struct TokuDb *db, const char *id);

/**
 * Update a book's reading status. `status` must be one of:
 * `want-to-read`, `reading`, `read`, `on-hold`, `did-not-finish`.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `id` must be a valid NUL-terminated UUID string.
 * - `status` must be a valid NUL-terminated status string.
 */
enum TokuStatus toku_update_book_status(struct TokuDb *db, const char *id, const char *status);

/**
 * Update a book's rating (0–10 scale). Pass -1 to clear the rating.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `id` must be a valid NUL-terminated UUID string.
 */
enum TokuStatus toku_update_book_rating(struct TokuDb *db, const char *id, int32_t rating);

/**
 * Log a reading-progress entry for a book.
 *
 * `progress_type` is one of `"page"`, `"percent"`, `"chapter"`, or `"duration"`
 * (minutes, for audiobooks). `value` is the corresponding page number, percentage
 * (0–100), chapter number, or minute count.
 *
 * Progress entries are immutable and append-only. When sync is configured, a
 * `progress` op is recorded so the entry flows through the op-log to other devices.
 * If an active reading session exists for the book, the entry is linked to it.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `id` must be a valid NUL-terminated UUID string.
 * - `progress_type` must be a valid NUL-terminated UTF-8 string.
 */
enum TokuStatus toku_log_progress(struct TokuDb *db,
                                  const char *id,
                                  const char *progress_type,
                                  int32_t value);

/**
 * Search books using full-text search. Results are returned as a JSON array.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `query` must be a valid NUL-terminated UTF-8 string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_search_books(struct TokuDb *db, const char *query, char **out_json);

/**
 * Get reading statistics as a JSON object. Pass `year = 0` for all-time stats,
 * or a specific year (e.g. 2025) for year-scoped stats.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_get_stats(struct TokuDb *db, int32_t year, char **out_json);

/**
 * List all tags with their counts as a JSON array.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_list_tags(struct TokuDb *db, char **out_json);

/**
 * Get tags for a specific book as a JSON array.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `id` must be a valid NUL-terminated UUID string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_get_book_tags(struct TokuDb *db, const char *id, char **out_json);

/**
 * List all shelves as a JSON array.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_list_shelves(struct TokuDb *db, char **out_json);

/**
 * Import books from a Goodreads CSV export. Returns an import report as JSON.
 * Set `dry_run` to true to preview without modifying the database.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `csv_path` must be a valid NUL-terminated file path.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_import_goodreads(struct TokuDb *db,
                                      const char *csv_path,
                                      bool dry_run,
                                      char **out_json);

/**
 * Initialize sync: register this device with the server, persist the auth token and
 * sync configuration under `data_dir`, and (optionally) enable client-side encryption.
 *
 * - `data_dir`: directory holding `toku.db` and `config.toml` (the app's data dir).
 * - `server`: sync server base URL (e.g. `https://sync.example.com`).
 * - `device_name`: human-readable device name, or null to derive one from the host name.
 * - `passphrase`: encryption passphrase, or null to disable encryption.
 *
 * On success, writes a JSON object describing the initialized sync state to `*out_json`.
 * The caller must free `*out_json` with `toku_free_string`.
 *
 * # Safety
 * - `data_dir` and `server` must be valid NUL-terminated UTF-8 strings.
 * - `device_name` and `passphrase` must each be null or a valid NUL-terminated UTF-8 string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_sync_init(const char *data_dir,
                               const char *server,
                               const char *device_name,
                               const char *passphrase,
                               char **out_json);

/**
 * Push all locally pending ops to the configured sync server.
 *
 * On success, writes a JSON object (`pushed`, `accepted`, `duplicates`, `cursor`,
 * `up_to_date`) to `*out_json`, which the caller must free with `toku_free_string`.
 *
 * # Safety
 * - `data_dir` must be a valid NUL-terminated UTF-8 string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_sync_push(const char *data_dir, char **out_json);

/**
 * Pull remote ops from the configured sync server and apply them locally.
 *
 * On success, writes a JSON object (`pulled`, `cursor`) to `*out_json`, which the
 * caller must free with `toku_free_string`.
 *
 * # Safety
 * - `data_dir` must be a valid NUL-terminated UTF-8 string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_sync_pull(const char *data_dir, char **out_json);

/**
 * Report the current sync status: configuration, pending op count, cursors, and the
 * number of registered devices.
 *
 * On success, writes a JSON object to `*out_json`, which the caller must free with
 * `toku_free_string`. Fails with `ErrorSync` if sync is not configured.
 *
 * # Safety
 * - `data_dir` must be a valid NUL-terminated UTF-8 string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_sync_status(const char *data_dir, char **out_json);

/**
 * List the devices registered to this library on the sync server, as a JSON array.
 *
 * On success, writes the array to `*out_json`, which the caller must free with
 * `toku_free_string`.
 *
 * # Safety
 * - `data_dir` must be a valid NUL-terminated UTF-8 string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_sync_devices(const char *data_dir, char **out_json);

/**
 * List unresolved sync conflicts awaiting user review, as a JSON array.
 *
 * On success, writes the array to `*out_json`, which the caller must free with
 * `toku_free_string`. Returns an empty array when there are no conflicts.
 *
 * # Safety
 * - `data_dir` must be a valid NUL-terminated UTF-8 string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_sync_conflicts(const char *data_dir, char **out_json);

/**
 * Resolve a single sync conflict, keeping the local or remote value.
 *
 * `keep` must be `"local"` or `"remote"`. On success, writes a JSON object
 * (`{ "resolved": bool }`) to `*out_json`, which the caller must free with
 * `toku_free_string`. `resolved` is `false` if the conflict was missing or
 * already resolved.
 *
 * # Safety
 * - `data_dir`, `id`, and `keep` must be valid NUL-terminated UTF-8 strings.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_sync_resolve_conflict(const char *data_dir,
                                           const char *id,
                                           const char *keep,
                                           char **out_json);

/**
 * Resolve every unresolved sync conflict with the same choice.
 *
 * `keep` must be `"local"` or `"remote"`. On success, writes a JSON object
 * (`{ "resolved": N }`) to `*out_json`, which the caller must free with
 * `toku_free_string`. `resolved` is the number of conflicts resolved.
 *
 * # Safety
 * - `data_dir` and `keep` must be valid NUL-terminated UTF-8 strings.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_sync_resolve_all_conflicts(const char *data_dir,
                                                const char *keep,
                                                char **out_json);

/**
 * Free a string that was allocated by a `toku_*` function. Passing null is a safe no-op.
 *
 * # Safety
 * `s` must be a string pointer previously returned by a `toku_*` function, or null.
 * Do not pass strings from other allocators.
 */
void toku_free_string(char *s);

#endif  /* TOKU_H */
