#ifndef TOKU_H
#define TOKU_H

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Result codes returned by all FFI functions.
 */
typedef enum TokuStatus {
  /**
   * Operation succeeded.
   */
  TOKU_STATUS_OK = 0,
  /**
   * A required pointer argument was null.
   */
  TOKU_STATUS_ERROR_NULL_POINTER = 1,
  /**
   * An input string was not valid UTF-8.
   */
  TOKU_STATUS_ERROR_INVALID_UTF8 = 2,
  /**
   * The requested resource was not found.
   */
  TOKU_STATUS_ERROR_NOT_FOUND = 3,
  /**
   * A database or I/O error occurred.
   */
  TOKU_STATUS_ERROR_DB = 4,
  /**
   * A Rust panic was caught at the FFI boundary.
   */
  TOKU_STATUS_ERROR_PANIC = 5,
} TokuStatus;

/**
 * Opaque handle to an open Toku database. Created by `toku_open`, destroyed by
 * `toku_close`. Do not inspect or modify the contents from C/Swift.
 */
typedef struct TokuDb TokuDb;

/**
 * Retrieve the last error message for the current thread. Returns null if no error
 * has occurred since the last successful call. The returned pointer is valid until
 * the next FFI call on this thread — do not free it.
 *
 * # Safety
 * This function accesses thread-local storage and returns a pointer that is valid
 * only until the next FFI call on the same thread.
 */
const char *toku_last_error(void);

/**
 * Open (or create) a Toku database at the given file path.
 * On success, writes a handle to `*out`. The caller must eventually call `toku_close`.
 *
 * # Safety
 * - `path` must be a valid NUL-terminated UTF-8 string.
 * - `out` must be a valid pointer to a `*mut TokuDb`.
 */
enum TokuStatus toku_open(const char *path, struct TokuDb **out);

/**
 * Close a Toku database handle and free its resources.
 * After this call, the handle must not be used. Passing null is a safe no-op.
 *
 * # Safety
 * `db` must be a handle previously returned by `toku_open`, or null.
 */
void toku_close(struct TokuDb *db);

/**
 * Add a book with a title and optional author. On success, writes the new book's
 * UUID string to `*out_id`. The caller must free `*out_id` with `toku_free_string`.
 *
 * Pass null for `author` to add a book without an author.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `title` must be a valid NUL-terminated UTF-8 string.
 * - `author` may be null, or a valid NUL-terminated UTF-8 string.
 * - `out_id` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_add_book(struct TokuDb *db,
                              const char *title,
                              const char *author,
                              char **out_id);

/**
 * List all books as a JSON array string. On success, writes the JSON string to
 * `*out_json`. The caller must free `*out_json` with `toku_free_string`.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_list_books(struct TokuDb *db, char **out_json);

/**
 * Get a single book by UUID as a JSON string. On success, writes the JSON string to
 * `*out_json`. Returns `ErrorNotFound` if no book matches the ID.
 * The caller must free `*out_json` with `toku_free_string`.
 *
 * # Safety
 * - `db` must be a valid handle from `toku_open`.
 * - `id` must be a valid NUL-terminated UUID string.
 * - `out_json` must be a valid pointer to a `*mut c_char`.
 */
enum TokuStatus toku_get_book(struct TokuDb *db, const char *id, char **out_json);

/**
 * Free a string that was allocated by a `toku_*` function. Passing null is a safe no-op.
 *
 * # Safety
 * `s` must be a string pointer previously returned by a `toku_*` function, or null.
 * Do not pass strings from other allocators.
 */
void toku_free_string(char *s);

#endif  /* TOKU_H */
